import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import {auth} from '../ts/firebase-user-setup'
import { signInWithPopup, GoogleAuthProvider } from "firebase/auth";
import {User} from '../ts/types'
import axios from 'axios'


export default function Home() {
 
  const [name, setName] = useState("")
  const [address, setAddress] = useState("")

  async function signup (){
      
      if(name && address){
        try{
            // sign up with google
            const provider = new GoogleAuthProvider();
            const result = await signInWithPopup(auth, provider)

            // The signed-in user info.
            const user = result.user;
            console.log({user})

            // save the user info
            const userInfo:User = {
              id:user.uid,
              name,
              address,
              email: user.email as string,
              phoneNumber: user.phoneNumber as string,
              emailVerified: user.emailVerified,
              type: 'merchant',
              dateCreated: Date.now(),
              profilePicture: user.photoURL as string
            }


            const res = await axios.post('/api/saveuser',userInfo)
            if(res.data.success) alert('saved successfully')
            else alert('failed to save!')

        }catch(error:any){
          alert(`failed to login with google!: ${error.message}`)
        }
        
         
      }
      else alert(`please provide valid information!`)
  }

  return (
    <>
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>
      <main className={styles.main}>

          <h1 className="text-3xl">Sign up to Next Multi Ecom Merchant</h1>
          <div className='flex items-center'>
            Name:
            <input onChange={e=>setName(e.target.value)} className='p-2 px-4' type="text" placeholder="enter your full name"/>
          </div>
          <div className='flex items-center'>
            Address:
            <textarea onChange={e=>setAddress(e.target.value)} className='p-2 px-4'  placeholder="enter your address" />
          </div>

          <button onClick={signup} className='p-2 px-4 bg-white rounded text-black'> Sign up with Google </button>
      </main>
    </>
  )
}
