import Head from 'next/head'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import {User} from '../ts/types'
import { getOneUser } from '@/database/users'



export const getStaticProps = async (context:any)=>{
    const uid = context.query?.user;
    console.log({uid})

    return {
        props: uid? await getOneUser(uid) : {}
    }
}


export default function Profile(user:User) {
  return (
    <>
      <Head>
        <title>My Profile | {user.name} </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>
      <main className='p-10'>
        <Link href="/" className="underline text-yellow-300">back</Link>
          <h1 className="text-3xl">{user.name}</h1>
          <div className='flex items-center pt-2'>
            <b>Address</b>: {user.address}
          </div>
           <div className='flex items-center pt-2'>
           <b>Email</b>: {user.email}
          </div>
          <div className='flex items-center pt-2'>
          <b>Account Type</b>: {user.type}
          </div>
      </main>
    </>
  )
}
